### ISSUE TITLE
DB Side: Create database and users

### ISSUE THREAD

**Issue by tessmichi** [Backgammon-/shrub#2]
[x] Use Nick's server to create DB.

[ ] Ensure to make a user for our app to use that is low privileged. Do not allow our app to use admin user or have any ability other than adding rows and reading rows (sin 16)

[ ] Pay attention to Sin 21 to make sure the right encryption is used

[x] Store: SHRUB username (req), SHRUB password (req), and github auth key (optional)

**Comment by tessmichi** [comment]
Tu and Nick (awaiting verification)

**Comment by Backgammon-** [comment]
Looked around, and it seems SQLCipher is a decent choice. Python binding: https://github.com/rigglemania/pysqlcipher3

**Comment by tessmichi** [comment]
Mike can you take lead on this?

**Comment by tessmichi** [comment]
Mike, do you want to work on making the DB and adding the cypher and users, and I'll work on the code to access the DB?

**Comment by Backgammon-** [comment]
Ok; there's some guides on using pysqlcipher floating around, I think not specifically python3 but they should be sufficiently similar. I had trouble correctly compiling everything correctly, I'm going to try again on a Linux environment and get it set up this evening.

**Comment by tessmichi** [comment]
Ok! And yes, I agree with SQLCipher. Thanks so much

**Comment by Backgammon-** [comment]
SQLCipher has no concept of users, so I'm not quite sure what to do here. The DB itself is encrypted, of course, but...

For password, I think we should store a bcrypt hash.

**Comment by tessmichi** [comment]
Sounds good to me. And I'm OK with ignoring the concept of using multiple users for the DB. I can simulate that as much as possible on the python side..
